# Generated by Django 4.0.5 on 2022-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0002_pictures_f_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures_f_posts',
            name='pict',
            field=models.ImageField(null=True, upload_to='posters_img/', verbose_name='Картинка'),
        ),
    ]
