# Generated by Django 4.0.5 on 2022-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0003_pictures_f_posts_pict'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures_f_posts',
            name='descriptiom',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание типа работы'),
        ),
    ]
