# Generated by Django 4.0.5 on 2022-06-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0005_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='url',
        ),
    ]
