# Generated by Django 4.0.5 on 2022-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0007_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='on_main',
            field=models.BooleanField(default=False, verbose_name='На главную(выводится только 3)'),
        ),
    ]
