# Generated by Django 4.0.5 on 2022-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0008_reviews_on_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='view_img',
            field=models.ImageField(default='view_img/demainer_form site.jpg', upload_to='view_img/', verbose_name='Картинка'),
        ),
    ]
