# Generated by Django 4.0.5 on 2022-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0009_reviews_view_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='Название')),
                ('discriptions', models.TextField(verbose_name='Описание ')),
                ('img', models.ImageField(upload_to='License_img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
    ]
