# Generated by Django 4.0.5 on 2022-07-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0013_alter_pictures_f_posts_descriptiom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1', models.TextField(default='Услуги', max_length=60, verbose_name='Ссылка-1(Прокрутка на блок с услугами)')),
                ('link_2', models.TextField(default='Лицензии', max_length=60, verbose_name='Ссылка-2(Открывает окно с лицензиями)')),
                ('link_3', models.TextField(default='Контакты', max_length=60, verbose_name='Ссылка-3(Прокрутка на блок с контактами)')),
                ('link_4', models.TextField(default='О нас', max_length=60, verbose_name='Ссылка-4(Открывает окно О НАС)')),
                ('link_5', models.TextField(default='Вакансии', max_length=60, verbose_name='Ссылка-5(Открывает окно с ВАКАНСИЯМИ)')),
                ('link_6', models.TextField(default='Заказчики', max_length=60, verbose_name='Ссылка-6(Открывает окно с ЗАКАЗЧИКАМИ)')),
                ('link_7', models.TextField(default='Отзывы', max_length=60, verbose_name='Ссылка-7(Прокрутка на блок с отзывами)')),
            ],
            options={
                'verbose_name': 'Название ссылок',
            },
        ),
        migrations.CreateModel(
            name='Main_Bg_pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image_change/image_main_bg', verbose_name='Картинка')),
                ('to_main', models.BooleanField(default=False, verbose_name='Показать на сайте')),
            ],
            options={
                'verbose_name': 'Картинка для заднего фона на главной',
                'verbose_name_plural': 'Картинки для заднего фона на главной',
            },
        ),
        migrations.CreateModel(
            name='Main_page_pict_and_txts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict_1', models.ImageField(upload_to='image_change/Main_page_pict', verbose_name='Картинка в блоке услуги')),
                ('pict_2', models.ImageField(upload_to='image_change/Main_page_pict', verbose_name='Картинка в блоке Оставить заявку')),
                ('txt_1_bold', models.TextField(max_length=300, verbose_name='Главный текст(Жирный)')),
                ('txt_1_usual', models.TextField(max_length=800, verbose_name='Главный текст(обычный)')),
                ('txt_2_bold', models.TextField(default='Проделанные работы', max_length=500, verbose_name='Блок с картинками(Жирный текст)')),
                ('txt_2_usual', models.TextField(default='Фотографии последних выездов', max_length=500, verbose_name='Блок с картинками(не Жирный текст)')),
                ('txt_serv_bold', models.TextField(default='С нами комфортно работать с момента обращения до сдачи работ.', max_length=500, verbose_name='Текст в блоке услугами()')),
                ('txt_serv_usual', models.TextField(default='Лучший сервис и поддержку по всем вопросам для наших клиентов.', max_length=800, verbose_name='Текст в блоке услугами')),
                ('txt_num_1', models.TextField(default='Солюдаем сроки', max_length=300, verbose_name='Текст-1(Жирный)')),
                ('txt_num_1_1', models.TextField(default='Прописываем в договоре каждый этап и дедлайн', max_length=500, verbose_name='Текст-1(обычный)')),
                ('txt_num_2', models.TextField(default='Энергоэффективность', max_length=300, verbose_name='Текст-2(Жирный)')),
                ('txt_num_2_1', models.TextField(default='Используем современную технику и оборудование', max_length=500, verbose_name='Текст-2(обычный)')),
                ('txt_num_3', models.TextField(default='Безопастность', max_length=300, verbose_name='Текст-3(Жирный)')),
                ('txt_num_3_1', models.TextField(default='Соблюдаем офицальный свод правил', max_length=500, verbose_name='Текст-3(обычный)')),
                ('txt_num_4', models.TextField(default='Серцифицирование', max_length=300, verbose_name='Текст-4(Жирный)')),
                ('txt_num_4_1', models.TextField(default='Имеем все соответствующие документы', max_length=500, verbose_name='Текст-4(обычный)')),
                ('txt_num_5', models.TextField(default='Прозрачная смета', max_length=300, verbose_name='Текст-5(Жирный)')),
                ('txt_num_5_1', models.TextField(default='Точная стоимость услуг до начала работ', max_length=500, verbose_name='Текст-5(обычный)')),
                ('txt_6', models.TextField(default='Оставить заявку на расчистку территории', max_length=200, verbose_name='Текст в форме отправки заявки(жирный)')),
                ('txt_6_1', models.TextField(default='Наш специалист свяжется с вами в ближайшее время', max_length=300, verbose_name='Текст в форме отправки заявки(обычный)')),
                ('txt_7', models.TextField(default='Отзывы наших клиентов', max_length=300, verbose_name='Текст в блоке отзывы')),
                ('telefon', models.TextField(default='+7(900)-999-99-99', max_length=20, verbose_name='Номер телефона')),
                ('info_email', models.EmailField(default='info@deminer.ru', max_length=200, verbose_name='Info_email')),
            ],
            options={
                'verbose_name': 'Текста и картинки на главной',
            },
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
