# Generated by Django 4.0.5 on 2022-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0015_alter_main_page_pict_and_txts_pict_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_page_pict_and_txts',
            name='pict_1',
            field=models.ImageField(upload_to='image_change/Main_page_pict', verbose_name='Картинка в блоке услуги'),
        ),
        migrations.AlterField(
            model_name='main_page_pict_and_txts',
            name='txt_1_bold',
            field=models.TextField(default='Очистка территории от взрывоопасных предметов.', max_length=300, verbose_name='Главный текст(Жирный)'),
        ),
        migrations.AlterField(
            model_name='main_page_pict_and_txts',
            name='txt_1_usual',
            field=models.TextField(default='В комплекс работ входит: поиск ВОП, обезвреживание, вывоз обнаруженных ВОП собственным спецтранспортом на полигон и организация утилизации (уничтожения).', max_length=800, verbose_name='Главный текст(обычный)'),
        ),
    ]
