# Generated by Django 4.0.5 on 2022-07-24 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0016_alter_main_page_pict_and_txts_pict_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures_f_posts',
            options={'verbose_name': 'Картинка для поста', 'verbose_name_plural': 'Картинки для постов'},
        ),
        migrations.AlterModelOptions(
            name='work_type',
            options={'verbose_name': 'Тип работ', 'verbose_name_plural': 'Типы работ'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='view_img',
        ),
        migrations.AddField(
            model_name='reviews',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='lesson_1.poster', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Отзыв'),
        ),
    ]
