# Generated by Django 4.0.5 on 2022-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0017_alter_pictures_f_posts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='view_img',
            field=models.ImageField(default='view_img/demainer_form site.jpg', upload_to='view_img/', verbose_name='Картинка'),
        ),
    ]
