# Generated by Django 4.0.5 on 2022-07-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0020_feedbackmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
