# Generated by Django 4.0.5 on 2022-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0021_alter_feedbackmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='email_phone',
            field=models.CharField(max_length=150, verbose_name='Email или телефон'),
        ),
    ]
