# Generated by Django 4.0.5 on 2022-07-31 00:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0023_feedbackmodel_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
