# Generated by Django 4.0.5 on 2022-07-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0024_alter_poster_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures_f_posts',
            name='descriptiom',
        ),
    ]
