# Generated by Django 4.0.5 on 2022-08-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0025_remove_pictures_f_posts_descriptiom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
