# Generated by Django 4.0.5 on 2022-08-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0026_delete_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='budgat',
        ),
    ]
