# Generated by Django 4.0.5 on 2022-08-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0028_remove_license_date_of_lic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='img',
        ),
        migrations.CreateModel(
            name='PictForLicences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict', models.ImageField(upload_to='LicenceImg/', verbose_name='Фотография или скан документа')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson_1.license', verbose_name='Прикрепить к')),
            ],
        ),
    ]
