# Generated by Django 4.0.6 on 2022-09-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0029_remove_license_img_pictforlicences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictforlicences',
            options={'verbose_name': 'Картинка у лицензии', 'verbose_name_plural': 'Картинки к лицензиям'},
        ),
    ]
