# Generated by Django 4.0.6 on 2022-09-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0032_works_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works_description',
            options={'verbose_name': 'Описание услуги'},
        ),
    ]
