# Generated by Django 4.0.6 on 2022-09-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0033_alter_works_description_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works_description',
            options={'verbose_name': 'Описание услуг'},
        ),
    ]
