# Generated by Django 4.0.6 on 2022-09-20 13:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0034_alter_works_description_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='works_description',
            name='imloding_work',
            field=ckeditor.fields.RichTextField(default=89, verbose_name='описание под заголовком'),
            preserve_default=False,
        ),
    ]
