# Generated by Django 4.0.6 on 2022-09-21 10:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0035_works_description_imloding_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works_description_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imloding_work', ckeditor.fields.RichTextField(verbose_name='описание под заголовком')),
                ('demining', ckeditor.fields.RichTextField(verbose_name='ОЧИСТКА МЕСТНОСТИ ОТ ВОП')),
                ('br_work', ckeditor.fields.RichTextField(verbose_name='БУРОВЗРЫВНЫЕ РАБОТЫ')),
                ('demolition', ckeditor.fields.RichTextField(verbose_name='ВАЛКА/СНОС НАПРАВЛЕННЫМ ВЗРЫВОМ ЗДАНИЙ И СООРУЖЕНИЙ')),
                ('explosive_destruction', ckeditor.fields.RichTextField(verbose_name='БЕЗВЗРЫВНОЕ РАЗРУШЕНИЕ СКАЛЬНЫХ ПАРОД И ЖБК')),
                ('design', ckeditor.fields.RichTextField(verbose_name='ПРОЕКТИРОВАНИЕ БВР')),
            ],
            options={
                'verbose_name': 'Краткое описание услуг для главной',
            },
        ),
    ]
