# Generated by Django 4.0.6 on 2022-09-21 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0037_delete_links_name_delete_main_page_pict_and_txts'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', ckeditor.fields.RichTextField(verbose_name='о нас')),
                ('equipment', ckeditor.fields.RichTextField(verbose_name='оборудование текст')),
                ('experience', ckeditor.fields.RichTextField(verbose_name='наш опыт')),
                ('standards', ckeditor.fields.RichTextField(verbose_name='соответсвие стандартам')),
            ],
            options={
                'verbose_name': 'о компании',
            },
        ),
        migrations.CreateModel(
            name='About_us_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', ckeditor.fields.RichTextField(verbose_name='оборудование')),
                ('experience', ckeditor.fields.RichTextField(verbose_name='наш опыт')),
                ('standards', ckeditor.fields.RichTextField(verbose_name='соответсвие стандартам')),
                ('customers', ckeditor.fields.RichTextField(verbose_name='заказчики')),
                ('vacancies', ckeditor.fields.RichTextField(verbose_name='вакансии')),
            ],
            options={
                'verbose_name': 'Краткое описание (о компании) для главной',
            },
        ),
    ]
