# Generated by Django 4.0.6 on 2022-09-21 14:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0038_about_us_about_us_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('equipment_img', models.ImageField(upload_to='Equipment_img/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='equipment',
        ),
    ]
