# Generated by Django 4.0.5 on 2022-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0039_equipment_remove_about_us_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezumFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email_phone', models.CharField(max_length=150, verbose_name='Email или телефон')),
                ('text', models.TextField(verbose_name='О человеке')),
                ('file_rez', models.FileField(upload_to='')),
                ('ready', models.BooleanField(default=False, verbose_name='Заявка закрыта')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
