# Generated by Django 4.0.5 on 2022-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0040_rezumformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezumformmodel',
            name='file_rez',
            field=models.FileField(upload_to='rezums/', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='rezumformmodel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='О человеке'),
        ),
    ]
